Add Pre-Update Callback Function Trigger to Parameter Update Process
pal-robotics/ddynamic_reconfigure pull request #28
Opened 2024-01-31 04:29 UTC by furushchev

Hi! I want to propose a new feature for this great library!

This pull request adds a trigger point for a callback function right before any parameter value is updated.
This enhancement complements the existing functionality where a callback can be called after the parameter update.

## Motivation
Some camera devices must stop streaming before changing settings and then restart it after the update.
This pre-update callback will provide users with the flexibility to programmatically handle such scenarios.

## Changes
- Added `setPreUpdateCallback` / `clearPreUpdateCallback`
- Added `setPostUpdateCallback` (which is identical to the original `setUserCallback`)

## Backward Compatibility
This change is fully backward compatible. (The original methods are kept as-is)
The new callback is optional and does not affect the existing workflow if not used.

2025-04-16 23:25 UTC, furushchev commented
@v-lopez Hello! Is there any chance to get this PR reviewed and merged, as the EOL of the ROS1 is comming soon?

2025-04-17 07:20 UTC, v-lopez commented
I can't merge this anymore, maybe @saikishor can review this.

2025-04-17 09:15 UTC, saikishor requested changes
@furushchev Sorry that I missed this PR. It would be great if you can add some tests for these newly added method. The changes itself look good to me.

2025-04-17 09:15 UTC, saikishor commented on include/ddynamic_reconfigure/ddynamic_reconfigure.h
> +  virtual void clearUserCallback();
If we stop using `setUserCallback` and replace it with `setPostUpdateCallback`, better to have it deprecated no?

2025-04-21 16:18 UTC, furushchev commented
@saikishor Thank you for your review!

> It would be great if you can add some tests for these newly added method

I updated the test code. Please let me know if we need some more test cases.

2025-04-21 16:19 UTC, furushchev commented on include/ddynamic_reconfigure/ddynamic_reconfigure.h
> +  virtual void clearUserCallback();
I agreed. the `setUserCallback` is already marked as deprecated function under the comment.

```
   /**                                                                                                                                                                      
    * Deprecated functions. For backwards compatibility, cannot be a template for legacy                                                                                    
    * reasons                                                                                                                                                               
    */
```

2025-04-22 08:05 UTC, saikishor approved these changes
LGTM. Thanks for the follow-up

2025-04-22 08:08 UTC, merged

2025-04-22 09:15 UTC, saikishor commented
@furushchev release is on its way https://github.com/ros/rosdistro/pull/45274

2025-04-22 15:40 UTC, furushchev commented
Thank you for your review and merge!

2025-07-28 13:16 UTC, peci1 commented
> This change is fully backward compatible. (The original methods are kept as-is)

It is not. It has removed the `user_callback_` member variable.

2025-07-28 13:23 UTC, saikishor commented
> > This change is fully backward compatible. (The original methods are kept as-is)
> 
> It is not. It has removed the `user_callback_` member variable.

ABI perspective it is not

2025-07-28 13:25 UTC, peci1 commented
This PR is not ABI-preserving at all. New member variables were added and new virtual functions, too.

2025-07-28 22:03 UTC, saikishor commented
> This PR is not ABI-preserving at all. New member variables were added and new virtual functions, too.

Okay, anyway ROS 1 is EOL. There is nothing much we can do